/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminDashboardBooksIndexRouteImport } from './routes/admin/dashboard/books/index'
import { Route as AdminDashboardBooksNewIndexRouteImport } from './routes/admin/dashboard/books/new/index'
import { Route as AdminDashboardBooksBook_idIndexRouteImport } from './routes/admin/dashboard/books/$book_id/index'
import { Route as AdminDashboardBooksBook_idEditIndexRouteImport } from './routes/admin/dashboard/books/$book_id/edit/index'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminDashboardBooksIndexRoute =
  AdminDashboardBooksIndexRouteImport.update({
    id: '/books/',
    path: '/books/',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardBooksNewIndexRoute =
  AdminDashboardBooksNewIndexRouteImport.update({
    id: '/books/new/',
    path: '/books/new/',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardBooksBook_idIndexRoute =
  AdminDashboardBooksBook_idIndexRouteImport.update({
    id: '/books/$book_id/',
    path: '/books/$book_id/',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardBooksBook_idEditIndexRoute =
  AdminDashboardBooksBook_idEditIndexRouteImport.update({
    id: '/books/$book_id/edit/',
    path: '/books/$book_id/edit/',
    getParentRoute: () => AdminDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/dashboard/books/': typeof AdminDashboardBooksIndexRoute
  '/admin/dashboard/books/$book_id/': typeof AdminDashboardBooksBook_idIndexRoute
  '/admin/dashboard/books/new/': typeof AdminDashboardBooksNewIndexRoute
  '/admin/dashboard/books/$book_id/edit/': typeof AdminDashboardBooksBook_idEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/dashboard/books': typeof AdminDashboardBooksIndexRoute
  '/admin/dashboard/books/$book_id': typeof AdminDashboardBooksBook_idIndexRoute
  '/admin/dashboard/books/new': typeof AdminDashboardBooksNewIndexRoute
  '/admin/dashboard/books/$book_id/edit': typeof AdminDashboardBooksBook_idEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/_main/': typeof MainIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/dashboard/books/': typeof AdminDashboardBooksIndexRoute
  '/admin/dashboard/books/$book_id/': typeof AdminDashboardBooksBook_idIndexRoute
  '/admin/dashboard/books/new/': typeof AdminDashboardBooksNewIndexRoute
  '/admin/dashboard/books/$book_id/edit/': typeof AdminDashboardBooksBook_idEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/admin/'
    | '/admin/dashboard/'
    | '/admin/dashboard/books/'
    | '/admin/dashboard/books/$book_id/'
    | '/admin/dashboard/books/new/'
    | '/admin/dashboard/books/$book_id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/dashboard/books'
    | '/admin/dashboard/books/$book_id'
    | '/admin/dashboard/books/new'
    | '/admin/dashboard/books/$book_id/edit'
  id:
    | '__root__'
    | '/_main'
    | '/admin/dashboard'
    | '/_main/'
    | '/admin/'
    | '/admin/dashboard/'
    | '/admin/dashboard/books/'
    | '/admin/dashboard/books/$book_id/'
    | '/admin/dashboard/books/new/'
    | '/admin/dashboard/books/$book_id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/books/': {
      id: '/admin/dashboard/books/'
      path: '/books'
      fullPath: '/admin/dashboard/books/'
      preLoaderRoute: typeof AdminDashboardBooksIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/books/new/': {
      id: '/admin/dashboard/books/new/'
      path: '/books/new'
      fullPath: '/admin/dashboard/books/new/'
      preLoaderRoute: typeof AdminDashboardBooksNewIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/books/$book_id/': {
      id: '/admin/dashboard/books/$book_id/'
      path: '/books/$book_id'
      fullPath: '/admin/dashboard/books/$book_id/'
      preLoaderRoute: typeof AdminDashboardBooksBook_idIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/admin/dashboard/books/$book_id/edit/': {
      id: '/admin/dashboard/books/$book_id/edit/'
      path: '/books/$book_id/edit'
      fullPath: '/admin/dashboard/books/$book_id/edit/'
      preLoaderRoute: typeof AdminDashboardBooksBook_idEditIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
  }
}

interface MainRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface AdminDashboardRouteChildren {
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardBooksIndexRoute: typeof AdminDashboardBooksIndexRoute
  AdminDashboardBooksBook_idIndexRoute: typeof AdminDashboardBooksBook_idIndexRoute
  AdminDashboardBooksNewIndexRoute: typeof AdminDashboardBooksNewIndexRoute
  AdminDashboardBooksBook_idEditIndexRoute: typeof AdminDashboardBooksBook_idEditIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardBooksIndexRoute: AdminDashboardBooksIndexRoute,
  AdminDashboardBooksBook_idIndexRoute: AdminDashboardBooksBook_idIndexRoute,
  AdminDashboardBooksNewIndexRoute: AdminDashboardBooksNewIndexRoute,
  AdminDashboardBooksBook_idEditIndexRoute:
    AdminDashboardBooksBook_idEditIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
