/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as BooksBook_idRouteImport } from './routes/books/$book_id'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminDashboardBooksIndexRouteImport } from './routes/admin/dashboard/books/index'
import { Route as AuthedDashboardLibraryIndexRouteImport } from './routes/_authed/dashboard/library/index'
import { Route as AuthedDashboardLibraryEbookRouteImport } from './routes/_authed/dashboard/library/$ebook'
import { Route as AdminDashboardBooksNewIndexRouteImport } from './routes/admin/dashboard/books/new/index'
import { Route as AdminDashboardBooksBook_idIndexRouteImport } from './routes/admin/dashboard/books/$book_id/index'
import { Route as AdminDashboardBooksBook_idEditIndexRouteImport } from './routes/admin/dashboard/books/$book_id/edit/index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBook_idRoute = BooksBook_idRouteImport.update({
  id: '/books/$book_id',
  path: '/books/$book_id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardBooksIndexRoute =
  AdminDashboardBooksIndexRouteImport.update({
    id: '/dashboard/books/',
    path: '/dashboard/books/',
    getParentRoute: () => AdminRoute,
  } as any)
const AuthedDashboardLibraryIndexRoute =
  AuthedDashboardLibraryIndexRouteImport.update({
    id: '/dashboard/library/',
    path: '/dashboard/library/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardLibraryEbookRoute =
  AuthedDashboardLibraryEbookRouteImport.update({
    id: '/dashboard/library/$ebook',
    path: '/dashboard/library/$ebook',
    getParentRoute: () => AuthedRoute,
  } as any)
const AdminDashboardBooksNewIndexRoute =
  AdminDashboardBooksNewIndexRouteImport.update({
    id: '/dashboard/books/new/',
    path: '/dashboard/books/new/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDashboardBooksBook_idIndexRoute =
  AdminDashboardBooksBook_idIndexRouteImport.update({
    id: '/dashboard/books/$book_id/',
    path: '/dashboard/books/$book_id/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDashboardBooksBook_idEditIndexRoute =
  AdminDashboardBooksBook_idEditIndexRouteImport.update({
    id: '/dashboard/books/$book_id/edit/',
    path: '/dashboard/books/$book_id/edit/',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/books/$book_id': typeof BooksBook_idRoute
  '/books/': typeof BooksIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/dashboard/library/$ebook': typeof AuthedDashboardLibraryEbookRoute
  '/dashboard/library/': typeof AuthedDashboardLibraryIndexRoute
  '/admin/dashboard/books/': typeof AdminDashboardBooksIndexRoute
  '/admin/dashboard/books/$book_id/': typeof AdminDashboardBooksBook_idIndexRoute
  '/admin/dashboard/books/new/': typeof AdminDashboardBooksNewIndexRoute
  '/admin/dashboard/books/$book_id/edit/': typeof AdminDashboardBooksBook_idEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/books/$book_id': typeof BooksBook_idRoute
  '/books': typeof BooksIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/dashboard/library/$ebook': typeof AuthedDashboardLibraryEbookRoute
  '/dashboard/library': typeof AuthedDashboardLibraryIndexRoute
  '/admin/dashboard/books': typeof AdminDashboardBooksIndexRoute
  '/admin/dashboard/books/$book_id': typeof AdminDashboardBooksBook_idIndexRoute
  '/admin/dashboard/books/new': typeof AdminDashboardBooksNewIndexRoute
  '/admin/dashboard/books/$book_id/edit': typeof AdminDashboardBooksBook_idEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/books/$book_id': typeof BooksBook_idRoute
  '/books/': typeof BooksIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/_authed/dashboard/library/$ebook': typeof AuthedDashboardLibraryEbookRoute
  '/_authed/dashboard/library/': typeof AuthedDashboardLibraryIndexRoute
  '/admin/dashboard/books/': typeof AdminDashboardBooksIndexRoute
  '/admin/dashboard/books/$book_id/': typeof AdminDashboardBooksBook_idIndexRoute
  '/admin/dashboard/books/new/': typeof AdminDashboardBooksNewIndexRoute
  '/admin/dashboard/books/$book_id/edit/': typeof AdminDashboardBooksBook_idEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/books/$book_id'
    | '/books/'
    | '/admin/dashboard/'
    | '/dashboard/library/$ebook'
    | '/dashboard/library/'
    | '/admin/dashboard/books/'
    | '/admin/dashboard/books/$book_id/'
    | '/admin/dashboard/books/new/'
    | '/admin/dashboard/books/$book_id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/books/$book_id'
    | '/books'
    | '/admin/dashboard'
    | '/dashboard/library/$ebook'
    | '/dashboard/library'
    | '/admin/dashboard/books'
    | '/admin/dashboard/books/$book_id'
    | '/admin/dashboard/books/new'
    | '/admin/dashboard/books/$book_id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/admin'
    | '/books/$book_id'
    | '/books/'
    | '/admin/dashboard/'
    | '/_authed/dashboard/library/$ebook'
    | '/_authed/dashboard/library/'
    | '/admin/dashboard/books/'
    | '/admin/dashboard/books/$book_id/'
    | '/admin/dashboard/books/new/'
    | '/admin/dashboard/books/$book_id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  BooksBook_idRoute: typeof BooksBook_idRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$book_id': {
      id: '/books/$book_id'
      path: '/books/$book_id'
      fullPath: '/books/$book_id'
      preLoaderRoute: typeof BooksBook_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard/books/': {
      id: '/admin/dashboard/books/'
      path: '/dashboard/books'
      fullPath: '/admin/dashboard/books/'
      preLoaderRoute: typeof AdminDashboardBooksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authed/dashboard/library/': {
      id: '/_authed/dashboard/library/'
      path: '/dashboard/library'
      fullPath: '/dashboard/library/'
      preLoaderRoute: typeof AuthedDashboardLibraryIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/library/$ebook': {
      id: '/_authed/dashboard/library/$ebook'
      path: '/dashboard/library/$ebook'
      fullPath: '/dashboard/library/$ebook'
      preLoaderRoute: typeof AuthedDashboardLibraryEbookRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/admin/dashboard/books/new/': {
      id: '/admin/dashboard/books/new/'
      path: '/dashboard/books/new'
      fullPath: '/admin/dashboard/books/new/'
      preLoaderRoute: typeof AdminDashboardBooksNewIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard/books/$book_id/': {
      id: '/admin/dashboard/books/$book_id/'
      path: '/dashboard/books/$book_id'
      fullPath: '/admin/dashboard/books/$book_id/'
      preLoaderRoute: typeof AdminDashboardBooksBook_idIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard/books/$book_id/edit/': {
      id: '/admin/dashboard/books/$book_id/edit/'
      path: '/dashboard/books/$book_id/edit'
      fullPath: '/admin/dashboard/books/$book_id/edit/'
      preLoaderRoute: typeof AdminDashboardBooksBook_idEditIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardLibraryEbookRoute: typeof AuthedDashboardLibraryEbookRoute
  AuthedDashboardLibraryIndexRoute: typeof AuthedDashboardLibraryIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardLibraryEbookRoute: AuthedDashboardLibraryEbookRoute,
  AuthedDashboardLibraryIndexRoute: AuthedDashboardLibraryIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AdminRouteChildren {
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminDashboardBooksIndexRoute: typeof AdminDashboardBooksIndexRoute
  AdminDashboardBooksBook_idIndexRoute: typeof AdminDashboardBooksBook_idIndexRoute
  AdminDashboardBooksNewIndexRoute: typeof AdminDashboardBooksNewIndexRoute
  AdminDashboardBooksBook_idEditIndexRoute: typeof AdminDashboardBooksBook_idEditIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminDashboardBooksIndexRoute: AdminDashboardBooksIndexRoute,
  AdminDashboardBooksBook_idIndexRoute: AdminDashboardBooksBook_idIndexRoute,
  AdminDashboardBooksNewIndexRoute: AdminDashboardBooksNewIndexRoute,
  AdminDashboardBooksBook_idEditIndexRoute:
    AdminDashboardBooksBook_idEditIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  BooksBook_idRoute: BooksBook_idRoute,
  BooksIndexRoute: BooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
