/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as BooksBook_idRouteImport } from './routes/books/$book_id'
import { Route as AdminBooksIndexRouteImport } from './routes/admin/books/index'
import { Route as AdminBooksNewIndexRouteImport } from './routes/admin/books/new/index'
import { Route as AuthedDashboardLibraryIndexRouteImport } from './routes/_authed/dashboard/library/index'
import { Route as AuthedDashboardLibraryEbookRouteImport } from './routes/_authed/dashboard/library/$ebook'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBook_idRoute = BooksBook_idRouteImport.update({
  id: '/books/$book_id',
  path: '/books/$book_id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksIndexRoute = AdminBooksIndexRouteImport.update({
  id: '/admin/books/',
  path: '/admin/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksNewIndexRoute = AdminBooksNewIndexRouteImport.update({
  id: '/admin/books/new/',
  path: '/admin/books/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardLibraryIndexRoute =
  AuthedDashboardLibraryIndexRouteImport.update({
    id: '/dashboard/library/',
    path: '/dashboard/library/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedDashboardLibraryEbookRoute =
  AuthedDashboardLibraryEbookRouteImport.update({
    id: '/dashboard/library/$ebook',
    path: '/dashboard/library/$ebook',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books/$book_id': typeof BooksBook_idRoute
  '/books/': typeof BooksIndexRoute
  '/admin/books/': typeof AdminBooksIndexRoute
  '/dashboard/library/$ebook': typeof AuthedDashboardLibraryEbookRoute
  '/dashboard/library/': typeof AuthedDashboardLibraryIndexRoute
  '/admin/books/new/': typeof AdminBooksNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books/$book_id': typeof BooksBook_idRoute
  '/books': typeof BooksIndexRoute
  '/admin/books': typeof AdminBooksIndexRoute
  '/dashboard/library/$ebook': typeof AuthedDashboardLibraryEbookRoute
  '/dashboard/library': typeof AuthedDashboardLibraryIndexRoute
  '/admin/books/new': typeof AdminBooksNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/books/$book_id': typeof BooksBook_idRoute
  '/books/': typeof BooksIndexRoute
  '/admin/books/': typeof AdminBooksIndexRoute
  '/_authed/dashboard/library/$ebook': typeof AuthedDashboardLibraryEbookRoute
  '/_authed/dashboard/library/': typeof AuthedDashboardLibraryIndexRoute
  '/admin/books/new/': typeof AdminBooksNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books/$book_id'
    | '/books/'
    | '/admin/books/'
    | '/dashboard/library/$ebook'
    | '/dashboard/library/'
    | '/admin/books/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books/$book_id'
    | '/books'
    | '/admin/books'
    | '/dashboard/library/$ebook'
    | '/dashboard/library'
    | '/admin/books/new'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/books/$book_id'
    | '/books/'
    | '/admin/books/'
    | '/_authed/dashboard/library/$ebook'
    | '/_authed/dashboard/library/'
    | '/admin/books/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  BooksBook_idRoute: typeof BooksBook_idRoute
  BooksIndexRoute: typeof BooksIndexRoute
  AdminBooksIndexRoute: typeof AdminBooksIndexRoute
  AdminBooksNewIndexRoute: typeof AdminBooksNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$book_id': {
      id: '/books/$book_id'
      path: '/books/$book_id'
      fullPath: '/books/$book_id'
      preLoaderRoute: typeof BooksBook_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books/': {
      id: '/admin/books/'
      path: '/admin/books'
      fullPath: '/admin/books/'
      preLoaderRoute: typeof AdminBooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books/new/': {
      id: '/admin/books/new/'
      path: '/admin/books/new'
      fullPath: '/admin/books/new/'
      preLoaderRoute: typeof AdminBooksNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/library/': {
      id: '/_authed/dashboard/library/'
      path: '/dashboard/library'
      fullPath: '/dashboard/library/'
      preLoaderRoute: typeof AuthedDashboardLibraryIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/library/$ebook': {
      id: '/_authed/dashboard/library/$ebook'
      path: '/dashboard/library/$ebook'
      fullPath: '/dashboard/library/$ebook'
      preLoaderRoute: typeof AuthedDashboardLibraryEbookRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardLibraryEbookRoute: typeof AuthedDashboardLibraryEbookRoute
  AuthedDashboardLibraryIndexRoute: typeof AuthedDashboardLibraryIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardLibraryEbookRoute: AuthedDashboardLibraryEbookRoute,
  AuthedDashboardLibraryIndexRoute: AuthedDashboardLibraryIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  BooksBook_idRoute: BooksBook_idRoute,
  BooksIndexRoute: BooksIndexRoute,
  AdminBooksIndexRoute: AdminBooksIndexRoute,
  AdminBooksNewIndexRoute: AdminBooksNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
